export const fallbackCategories = [
  { name: "Treadmills", slug: "treadmills", description: "Running machines for home and commercial training.", image: "https://images.unsplash.com/photo-1538805060514-97d9cc17730c?auto=format&fit=crop&w=1000&q=85" },
  { name: "Bikes", slug: "exercise-bikes", description: "Connected cycling, ride classes and indoor endurance.", image: "https://images.unsplash.com/photo-1594737625785-a6cbdabd333c?auto=format&fit=crop&w=1000&q=85" },
  { name: "Ellipticals", slug: "ellipticals", description: "Low impact cardio with immersive digital programs.", image: "https://images.unsplash.com/photo-1571019613914-85f342c6a11e?auto=format&fit=crop&w=1000&q=85" },
  { name: "Rower", slug: "rower", description: "Total body rowing experience for performance users.", image: "https://images.unsplash.com/photo-1599058917212-d750089bc07e?auto=format&fit=crop&w=1000&q=85" },
  { name: "Stair Climbers", slug: "stair-climbers", description: "High intensity climbing machines for gyms and clubs.", image: "https://images.unsplash.com/photo-1570829460005-c840387bb1ca?auto=format&fit=crop&w=1000&q=85" },
  { name: "Multi Gyms", slug: "multi-gyms", description: "Compact full body strength stations.", image: "https://images.unsplash.com/photo-1540497077202-7c8a3999166f?auto=format&fit=crop&w=1000&q=85" },
  { name: "Dumbbells & Kettlebells", slug: "free-weights", description: "Premium free weights and functional tools.", image: "https://images.unsplash.com/photo-1517963879433-6ad2b056d712?auto=format&fit=crop&w=1000&q=85" },
  { name: "Benches", slug: "benches", description: "Stable workout benches for every strength setup.", image: "https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?auto=format&fit=crop&w=1000&q=85" },
];

export const fallbackProducts = [
  { name: "Technogym MyRun", slug: "technogym-myrun", category: "Treadmills", price: "INR 4,00,000", numericPrice: 400000, tag: "Home bestseller", description: "Compact connected treadmill with guided running and refined design.", shortDescription: "Compact connected treadmill.", image: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?auto=format&fit=crop&w=1200&q=85", specs: ["Compact footprint", "Connected app training", "Quiet home operation", "Premium display support"], isFeatured: true },
  { name: "Run Personal", slug: "run-personal", category: "Treadmills", price: "INR 8,90,000", numericPrice: 890000, tag: "Designer line", description: "Luxury treadmill for villas, suites and high-end training rooms.", shortDescription: "Luxury treadmill.", image: "https://images.unsplash.com/photo-1571019613914-85f342c6a11e?auto=format&fit=crop&w=1200&q=85", specs: ["Large running surface", "Luxury finish", "Entertainment ready", "Professional motor"], isFeatured: true },
  { name: "Skillrun", slug: "skillrun", category: "Treadmills", price: "Request price", numericPrice: 0, tag: "Commercial", description: "Performance treadmill concept for athletic and club environments.", shortDescription: "Performance treadmill.", image: "https://images.unsplash.com/photo-1538805060514-97d9cc17730c?auto=format&fit=crop&w=1200&q=85", specs: ["Athletic performance", "Commercial grade", "Power training", "Smart console"], isFeatured: true },
  { name: "Technogym Bike", slug: "technogym-bike", category: "Bikes", price: "INR 4,25,000", numericPrice: 425000, tag: "Connected", description: "Premium indoor bike with immersive training and sleek home form factor.", shortDescription: "Premium indoor bike.", image: "https://images.unsplash.com/photo-1594737625785-a6cbdabd333c?auto=format&fit=crop&w=1200&q=85", specs: ["Live workouts", "Silent resistance", "Compact design", "Connected console"], isFeatured: true },
  { name: "Technogym Ride", slug: "technogym-ride", category: "Bikes", price: "INR 5,25,000", numericPrice: 525000, tag: "Cyclist choice", description: "Indoor cycling platform built for serious riders and data-led training.", shortDescription: "Indoor cycling platform.", image: "https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=1200&q=85", specs: ["Road feel", "Training metrics", "Smart resistance", "Compact footprint"], isFeatured: true },
  { name: "Skillrow", slug: "skillrow", category: "Rower", price: "INR 4,80,000", numericPrice: 480000, tag: "Full body", description: "Athletic rowing machine for endurance, strength and total body training.", shortDescription: "Full body rowing machine.", image: "https://images.unsplash.com/photo-1599058917212-d750089bc07e?auto=format&fit=crop&w=1200&q=85", specs: ["Aquafeel resistance", "Power training", "Compact frame", "Team workouts"], isFeatured: true },
  { name: "Technogym Bench", slug: "technogym-bench", category: "Benches", price: "INR 1,65,000", numericPrice: 165000, tag: "Home gym essential", description: "Compact bench with hidden tools for complete functional home training.", shortDescription: "Compact workout bench.", image: "https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?auto=format&fit=crop&w=1200&q=85", specs: ["Integrated tools", "Small footprint", "Full body workouts", "Designer finish"], isFeatured: true },
  { name: "Unica Strength", slug: "unica-strength", category: "Multi Gyms", price: "INR 7,40,000", numericPrice: 740000, tag: "Strength station", description: "All-in-one strength station for private homes and premium wellness rooms.", shortDescription: "All-in-one strength station.", image: "https://images.unsplash.com/photo-1540497077202-7c8a3999166f?auto=format&fit=crop&w=1200&q=85", specs: ["Complete strength", "Luxury finish", "Guided movement", "Small footprint"], isFeatured: true },
];
